/**
 * One-time / reproducible font vendoring (AUDIT A2, constraint C1: no runtime CDN).
 *
 * Downloads the LATIN-subset woff2 files for Inter (UI) and Outfit (display /
 * numeric) from Google Fonts and writes them to src/assets/fonts/ together with
 * a self-contained @font-face stylesheet (fonts.css). The app then loads fonts
 * from its own origin — the prototype's fonts.googleapis.com dependency is gone.
 *
 * Material Symbols are NOT fetched: the app uses inline SVG icons instead, which
 * also removes U5 (icon ligature announced as the accessible name).
 *
 * Run manually when the font set changes:  node scripts/fetch-fonts.mjs
 * The downloaded woff2 files are committed, so normal build/dev needs no network.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(repoRoot, 'src', 'assets', 'fonts');
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Outfit:wght@400;500;600;700&display=swap';

mkdirSync(outDir, { recursive: true });

const cssRes = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
if (!cssRes.ok) throw new Error(`Font CSS fetch failed: ${cssRes.status}`);
const css = await cssRes.text();

// Split into @font-face blocks, each preceded by a /* subset */ comment.
const blockRe = /\/\*\s*(?<subset>[a-z0-9-]+)\s*\*\/\s*@font-face\s*\{(?<body>[^}]*)\}/g;
const faces = [];
for (const m of css.matchAll(blockRe)) {
  const { subset, body } = m.groups;
  if (subset !== 'latin') continue; // Latin-only UI keeps the payload small.
  const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(body)?.[1];
  const url = /src:\s*url\(([^)]+)\)/.exec(body)?.[1];
  if (family && weight && url) faces.push({ family, weight, url });
}

if (faces.length !== 8) {
  throw new Error(`Expected 8 latin faces (2 families x 4 weights), got ${faces.length}`);
}

const cssLines = [
  '/* Self-hosted fonts (A2/C1) — generated by scripts/fetch-fonts.mjs. Do not edit by hand. */',
];
for (const face of faces) {
  const file = `${face.family.toLowerCase()}-${face.weight}.woff2`;
  const woff2 = await fetch(face.url, { headers: { 'User-Agent': UA } });
  if (!woff2.ok) throw new Error(`woff2 fetch failed for ${file}: ${woff2.status}`);
  const buf = Buffer.from(await woff2.arrayBuffer());
  writeFileSync(join(outDir, file), buf);
  console.log(`[fetch-fonts] ${file} (${(buf.length / 1024).toFixed(1)} kB)`);
  cssLines.push(
    '@font-face {',
    `  font-family: '${face.family}';`,
    '  font-style: normal;',
    `  font-weight: ${face.weight};`,
    '  font-display: swap;',
    `  src: url('./fonts/${file}') format('woff2');`,
    '}',
  );
}

writeFileSync(join(outDir, 'fonts.css'), cssLines.join('\n') + '\n');
console.log(`[fetch-fonts] wrote ${faces.length} @font-face rules to fonts.css`);
